# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:53:02+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity
from fastapi import Query

from models import About, Ec

app = MCPProxy(
    description='Analyzes a password and calculates its entropy.',
    title='Arespass',
    version='1.0',
    servers=[{'url': 'http://arespass.net/v1.0'}],
)


@app.get('/about', tags=['api_metadata'])
def get_about(output_format: Optional[str] = Query(None, alias='outputFormat')):
    """
        Metadata about this API&#58; version number, release date and available languages.

    Metadata requests are NOT billed.

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get('/ec', tags=['password_entropy_analysis'])
def get_ec(
    password: str,
    output_format: Optional[str] = Query(None, alias='outputFormat'),
    penalty: Optional[float] = None,
    req_id: Optional[str] = Query(None, alias='reqId'),
):
    """
        The entropy calculator - alias ec -, analyzes a password and calculates its entropy.

    Entropy calculator requests are billed.

    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
