# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:53:02+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class ApiVersion(BaseModel):
    majorNumber: Optional[int] = Field(
        None, description='This API version major number.'
    )
    minorNumber: Optional[int] = Field(
        None, description='This API version minor number.'
    )


class About(BaseModel):
    apiReleaseDateIso8601: Optional[str] = Field(
        None, description='**The release date of this API, ISO 8601 format.**\n'
    )
    apiVersion: Optional[ApiVersion] = None
    availableLanguagesIso639_1: Optional[str] = Field(
        None,
        description='**The list of available languages.**\n\nEach language is identified by its ISO 639-1, two-letter code.\n\nThe list elements are comma-separated and sorted in ascending order.\n',
    )


class AlphabetSequenceItem(BaseModel):
    char: Optional[str] = Field(None, description='The n-th character.')
    l33tchar: Optional[str] = Field(
        None, description='The n-th character after the l33t transformation.'
    )
    penalty: Optional[float] = Field(
        None,
        description='The penalty applied to this character if it is part of an alphabet sequence.\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )


class EntropyDistributionItem(BaseModel):
    char: Optional[str] = Field(None, description='The n-th character.')
    l33tchar: Optional[str] = Field(
        None, description='The n-th character after the l33t transformation.'
    )
    percentage: Optional[float] = Field(
        None,
        description='The amount of entropy contributed by this character, expressed as percentage of the total.',
    )


class KeyboardSequenceItem(BaseModel):
    char: Optional[str] = Field(None, description='The n-th character.')
    l33tchar: Optional[str] = Field(
        None, description='The n-th character after the l33t transformation.'
    )
    penalty: Optional[float] = Field(
        None,
        description='The penalty applied to this character if it is part of a keyboard sequence.\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )


class NumberSequenceItem(BaseModel):
    char: Optional[str] = Field(None, description='The n-th character.')
    l33tchar: Optional[str] = Field(
        None, description='The n-th character after the l33t transformation.'
    )
    penalty: Optional[float] = Field(
        None,
        description='The penalty applied to this character if it is part of a number sequence.\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )


class RepeatedChar(BaseModel):
    char: Optional[str] = Field(None, description='The n-th character.')
    l33tchar: Optional[str] = Field(
        None, description='The n-th character after the l33t transformation.'
    )
    penalty: Optional[float] = Field(
        None,
        description='The penalty applied to this character if it is repeated.\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )


class TotalItem(BaseModel):
    char: Optional[str] = Field(None, description='The n-th character.')
    l33tchar: Optional[str] = Field(
        None, description='The n-th character after the l33t transformation.'
    )
    penalty: Optional[float] = Field(
        None,
        description='The total penalty applied to each character.\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.                \n',
    )


class Word(BaseModel):
    char: Optional[str] = Field(None, description='The n-th character.')
    l33tchar: Optional[str] = Field(
        None, description='The n-th character after the l33t transformation.'
    )
    penalty: Optional[float] = Field(
        None,
        description='The penalty applied to this character if it is part of a word.\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.                \n',
    )


class Ec(BaseModel):
    alphabetSequence: Optional[List[AlphabetSequenceItem]] = Field(
        None,
        description='**The penalty applied to each character that has been found to be part of an alphabet sequence.**\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )
    apiVersion: Optional[str] = Field(
        None, description='**This API version number.**\n'
    )
    detectedKeyboard: Optional[str] = Field(
        None, description='**The detected keyboard, QWERTY or Dvorak.**\n'
    )
    efficiency: Optional[float] = Field(
        None,
        description='**The ratio entropy / idealEntropy.**\n\nIt is a float number in the range [0, 1].\n',
    )
    entropy: Optional[float] = Field(
        None,
        description='**The entropy calculated for the input password.**\n\nIt is measured in bits.\n',
    )
    entropyDistribution: Optional[List[EntropyDistributionItem]] = Field(
        None,
        description='**The distribution of the calculated entropy among the password characters.**\n',
    )
    idealEntropy: Optional[float] = Field(
        None,
        description='**The Shannon entropy.**\n\nThe Shannon entropy is the entropy calculated if no penalizations - words, number sequence, alphabet sequence, etc - were found in the password.\n\nIt is measured in bits.\n',
    )
    keyboardSequence: Optional[List[KeyboardSequenceItem]] = Field(
        None,
        description='**The penalty applied to each character that has been found to be part of a keyboard sequence.**\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )
    l33tPassword: Optional[str] = Field(
        None, description='The analyzed password after the l33t substitution.'
    )
    nonUniformEntropyDistributionPenalty: Optional[float] = Field(
        None,
        description='**The penalty applied to the whole password because of irregular entropy distribution.**\n\nThis penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )
    numberSequence: Optional[List[NumberSequenceItem]] = Field(
        None,
        description='**The penalty applied to each character that has been found to be part of a number sequence.**\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )
    password: Optional[str] = Field(None, description='The analyzed password.')
    passwordLength: Optional[int] = Field(
        None, description='The number of characters the password has.'
    )
    penalty: Optional[float] = Field(
        None,
        description='**The penalty applied to each character that has been found to be part of a word, number sequence, alphabet sequence, etc.**\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n\nIts value is equal to the value of the input parameter *penalty*.\n',
    )
    repeatedChars: Optional[List[RepeatedChar]] = Field(
        None,
        description='**The penalty applied to each character that are repeated**\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.          \n',
    )
    requestId: Optional[str] = Field(
        None,
        description='**The identifier of the request that corresponds to this response.**\n',
    )
    requestTimestamp: Optional[float] = Field(
        None,
        description='**The timestamp for this response.**\n\nMilliseconds from the epoch of 1970-01-01T00:00:00Z.\n',
    )
    summary: Optional[List[str]] = None
    total: Optional[List[TotalItem]] = Field(
        None,
        description='**The total penalty applied to each character.**\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )
    words: Optional[List[Word]] = Field(
        None,
        description='**The penalty applied to each character that has been found to be part of a word.**\n\nThe penalty is a float number in the range [0, 1]. Full penalty, 0; no penalty, 1.\n',
    )
